### ISSUE TITLE
Skills with only 1 point are not being displayed on the actor sheet

### ISSUE THREAD

**Issue by dmpunks** [Genii-Locorum/outgunned#17]
The Actor Sheet seem to be excluding 1 point Skills from being displayed:

![image](https://github.com/user-attachments/assets/ba34568e-c328-4b10-9510-92ed359b3c2e)

**Comment by dmpunks** [comment]
This seems related also: When adding Bonus Skill Points to Skills that are at 1 point, they are displayed as 1 point skills on the sheet. 

Steps to Reproduce:
1. Create a new character with the following age, role and trope:

- Age = Adult
- Role = Ace
- Trope = Free Spirit

2. Assign the 2 free skill points to any skills that are not shown on the sheet.

Actual behavior: The assigned skills now show up as 1-point skills instead of 2.

Expected behavior: The skills should be 2-point skills since all Heroes start with 1 skill point in all Skills.

**Comment by Genii-Locorum** [comment]
@dmpunks - thanks for this.  Can you provide screenshots of the Adult, Ace and Free Spirit tropes.

When you first create the new character do you see the one point skills?

<img width="360" alt="image" src="https://github.com/user-attachments/assets/b335eea5-0d14-44bc-9246-e256d5e8b583" />

Cheers

**Comment by dmpunks** [comment]
Hi @Genii-Locorum,

Looks like I'm unable to reproduce this anymore after ensuring that all my items are imported (Ages, Roles, Tropes, Skills and Feats). I guess it's good to keep them in the World rather than in Compendiums since there seems to be a small number of them compared to other games but is there really no alternative way to just keep them in compendiums? 

Thanks a lot for the system btw. Looking forward to running for my group. Happy New Year!

**Comment by Genii-Locorum** [comment]
Thanks for the reply @dmpunks .  I now understand the issue.  

Short Answer - Outgunned doesn't use compendiums - just items in the game world, so all items etc need to be in world.

Longer Answer - I was asked to write a system as part of a teaching exercise on how to create a new system - using Outgunned as the example.  I did the initial system but the teaching bit didn't come to fruition - so Outgunned was a very basic system with a few different ways of doing the same thing,  It was sort of mothballed but then someone heard about it and asked me to release .  So I hasn't gone all the bells and whistles such as using compendium.  A few bits have been added as we've gone along (such as the Outgunned dice) when I've had time to dig in Foundry some more.

At the moment my time is spread very thinly over a number of systems, work, family, other hobbies - so I'm unlikely to  get round to some changes to deal with compendiums anytime soon.  (I have done it in other systems, but needed to use a bespoke ID setup so all versions of the same skill for example get de-duped when producing lists based on a "keyword" rather than just the item name - the system I used is pretty much a clone of the Call of Cthulhu ID system which works really well).

If someone wanted to pick up the code and work on changes then perhaps it'll get done sooner :-)

Have a great New Year.

Cheers
