### ISSUE TITLE
Feature Request: Additional Weapon Feats

### ISSUE THREAD

**Issue by NerdEyeIndustries** [Genii-Locorum/outgunned#5]
Please add the additional weapon feats found in Action Flicks/World of Killers (and presumably the new OG Adventure will have new/different ones).

**Comment by Genii-Locorum** [comment]
I can't because the arrangement I have with Two Little Mice is to only include things from the free starter set.  By including lots of extra stuff it would run the risk of people not buying the games/rule books etc so I am completely with TLM on this.

You can create them in your own games though and share them between your own games/worlds. with the Foundry Module Options.

**Comment by NerdEyeIndustries** [comment]
>I can't because the arrangement I have with Two Little Mice is to only include things from the free starter set. 

So this is a useless ruleset beyond the core book? Thats unfortunate.

>You can create them in your own games though and share them between your own games/worlds. with the Foundry Module Options.

Hmm, how exactly? You cannot add any weapon that requires the additional feats and there's no place to add them.
